### ISSUE TITLE
Local resovle

### ISSUE THREAD

**Issue by andylokandy** [dcao/elba#8]
I've got a main package:

```toml
[package]
name = "Andy/Hello"
version = "0.1.0"
authors = []

[dependencies]
"Util/Dep" = { path="K:\\Code\\Idris\\Dep" }

[[targets.bin]]
name = "Hello"
main = "src/Main.idr"
```

Also I've got the dep package right at `K:\Code\Idris\Dep`:

```toml
[package]
name = "Util/Dep"
version = "0.1.0"
authors = []

[dependencies]

[[targets.lib]]
path = "src"
mods = "Dep"
```

Then when I build the root:
```shell
K:\Code\Idris\Hello
$ K:\Code\Rust\elba\target\debug\elba build
[1/4] Updating package indices...
  [inf] Indices stored at C:\Users\Andy\.elba\indices
[2/4] Resolving dependencies...

[err] version solving has failed

Because Util/Dep@dir+K:\Code\Idris\Dep any is unavailable and Andy/Hello@root >=0.1.0 <=0.1.0 depends on Util/Dep@dir+K:\Code\Idris\Dep any, Andy/Hello@root >=0.1.0 <=0.1.0 is impossible.
```
